title: PQuan Studio
email: pquanapps@gmail.com
description: Write the Code. Change the World.
author: PQuan Studio
baseurl: ""
url: ""

# Build settings
paginate: 5
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-paginate



